export const GET_ALL_NOTIFICATIONS = 'GET_ALL_NOTIFICATIONS'
export const SHOW_DETAIL_NOTIFICATIONS = 'SHOW_DETAIL_NOTIFICATIONS'

export const CREATE_NOTIFICATION = 'CREATE_NOTIFICATION'

export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION'